### ISSUE TITLE
Lorentz bug: correlator on unit gaugefield with periodic BC is not identical in all four directions

### ISSUE THREAD

**Issue by m-schroeck** [etmc/tmLQCD#304] opened 2015-08-18 16:25 UTC
-set unit gaugefield
-set source to zero except on site ix=0, there set it to 1 for all color and spin indices
-set boundary conditions to periodic in all four directions
-set the same lattice size in all four directions
-invert the twisted mass operator on that source
-construct (pion like) correlator along each space-time dimension, e.g. along t with x=y=z=0 and equivalently along x,y,z with the other indices zero
-the four resulting correlators should be the same, but only two agree (along y and z), the other two are not even symmetric!

![lorentz-bug](https://cloud.githubusercontent.com/assets/7427142/9335611/4204f77e-45d5-11e5-9f08-c831f89a8c01.png)

To reproduce the bug, see https://github.com/m-schroeck/tmLQCD/tree/lorentz-bug which contains minimal changes from invert.c and an adequate input file which is:

>L = 16            
>T = 16
>
>DebugLevel = 3
>2kappaMu = 0.05
>kappa = 0.177
>BCAngleT = 0
>DisableIOChecks = yes
>UseRelativePrecision = no
>UseEvenOdd = yes
>OmpNumThreads = 1
>NoSamples = 1
>SourceType = Volume
>
>BeginOperator TMWILSON
>  2kappaMu = 0.05
>  kappa = 0.177
>  UseEvenOdd = yes
>  Solver = CG
>  SolverPrecision = 1e-20
>  MaxSolverIterations = 10000
>EndOperator

Details: most basic configure: CC=mpiicc --disable-omp --disable-mpi --disable-gaugecopy --disable-halfspinor --with-limedir=${limedir} --with-lapack="-mkl=parallel"
Compiler: icc (ICC) 15.0.2 20150121

Please try to reproduce the bug. In case I'm doing something stupid, please let me know :)

**Comment by m-schroeck** [comment] 2015-08-18 19:50
Exact same problem with
gcc (GCC) 4.9.2

**Comment by urbach** [comment] 2016-05-18 10:04
@kostrzewa @m-schroeck okay, started to look into this. First observation is that the averaged correlators (forward/backward) are identical for all 4 directions

**Comment by urbach** [comment] 2016-05-18 10:05
now, if I use a different source, namely delta sources for instance like this

    for( int is=3; is<4; is++ )
       for( int ic=2; ic<3; ic++ ) {
          p_cplx_src[is*3+ic] = 1.0;
       }

for all possible spin/colour combinations, I get identical correlators in all four directions

**Comment by urbach** [comment] 2016-05-18 10:10
the same if there is a 1 in all three colour components

**Comment by urbach** [comment] 2016-05-18 10:14
now I set two spin components at the same time, like this

    for( int is=1; is<3; is++ )
       for( int ic=0; ic<3; ic++ ) {
          p_cplx_src[is*3+ic] = 1.0;
      }

for is=(1,2) and is=(3,4) all correlators are identical, for is=(2,3) X and Y differ from identical T and Z

**Comment by urbach** [comment] 2016-05-18 10:17
adding the combinations is=(0,2) and is=(1,3), for which T and Z differ from identical X and Y

**Comment by urbach** [comment] 2016-05-18 10:41
with twisted mass set to zero the discrepancy is only in the T direction

**Comment by urbach** [comment] 2016-05-18 13:17
Why was the source chosen like this? 

With delta sources we get the correct result. Setting all 12 elements to 1 leads to unwanted contributions in the inverse. And they'll not cancel (which they would in the full theory due to gauge invariance). Might this explain the seen effect?

**Comment by m-schroeck** [comment] 2016-05-18 13:23
Hi Carsten,
I had chosen the source like that not for physical reasons but while trying to match the tmLQCD operator with the qphix tm operator. 
Mario

**Comment by urbach** [comment] 2016-05-18 13:43
and you are saying this does not happen with the qphix tm operator?

Independently of this, this source mixes all gamma matrices in in the correlator, doesn't it?

**Comment by m-schroeck** [comment] 2016-05-18 13:47
Well, I still had problems matching the two operators but as far as I can remember that didn't occur in the qphix operator. I've tested this as a step towards sources with Zn noise.

**Comment by urbach** [comment] 2016-05-18 13:51
with stochastic sources the story is different.

When we test the result of the Quda inverter, we do not observe a deviation, correct? @kostrzewa

**Comment by m-schroeck** [comment] 2016-05-18 13:54
I don't think that this occurs with Quda

**Comment by urbach** [comment] 2016-05-18 13:56
but we cross-check the propagator produced by Quda. We should see a deviation, if there is any, shouldn't we?

**Comment by m-schroeck** [comment] 2016-05-18 13:58
You're right, the actual operators agree when comparing tmLQCD and Quda..

**Comment by kostrzewa** [comment] 2016-05-18 14:07
After fixing the residual definitions (such that both QUDA and tmLQCD compute the inverse of (D D^dagger) and post-multiply with D^dagger to get D^(-1), the residuals reported by QUDA and the one in the post-inversion check of tmLQCD are always of the same order of magnitude and most of the time agree to some significant digit. If that is the case, I do not see how the resulting correlators could disagree. I did not do any tests using trivial gauge configurations. I did test with point sources and stochastic sources of various kinds, however.

**Comment by m-schroeck** [comment] 2016-05-18 14:15
I'm not saying it's a bug in the actual operator. But as far as I remember, when I tested the same thing completely independent of tmLQCD with e.g. Quda I didn't find that behavior.

**Comment by kostrzewa** [comment] 2016-05-18 14:16
Does it also happen with the halfspinor operator?

**Comment by kostrzewa** [comment] 2016-05-18 14:17
Oh, yes I remember it does. You tested that in our last exchange.

**Comment by urbach** [comment] 2016-05-18 14:41
it would be interesting to try tmLQCD with Quda inverter. Can the Quda inverter be called from your branch, Mario?

to sum up:
 * with point sources it does not appear
 * averaging C(+t) and C(-t) gets rid of the deviation
 * Quda and tmLQCD agree for the propagator to some precision when Quda is called from tmLQCD
 * setting the twisted mass value to zero reduces the deviation to only one direction, namely T
 * it is independent of gauge copy/ halfspinor

correct?

What do we expect for this kind of source?

**Comment by kostrzewa** [comment] 2016-05-18 14:45
> Can the Quda inverter be called from your branch, Mario?

no, we pulled in the quda interface a long time after this bug was submitted

**Comment by urbach** [comment] 2016-05-18 14:47
but we could copy `invert.c`

**Comment by urbach** [comment] 2016-05-18 15:26
Also after some discussion with Bartek, it seems to me that this is not a bug, but due to the special source choice: due to the source you will not compute the "pion" correlator, but a mixture of all possible gamma-matrices at sink. If one of these happens to be a `sinh`, it can explain the observed behaviour. And due to the mixture the correlators also get some dependence on the direction.

For me the biggest evidence for the above explained scenario is that when I use point source (i.e. delta in spin and colour), there is no dependence on the direction and by multiplying the correlator with a factor of 12 I get the same result as in the Y and Z direction with "wall source". Moreover, a `sinh` contributions gets averaged out when +t and -t are averaged.

This can be further checked in the following way:
 * sum up the 12 propagators obtained with delta sources and compare to the one propagator obtained with the "wall source". They should agree.
 * compute the properties of the correlators obtained with the "wall source" and verify or falsify the scenario explained above.

Does this make sense?

**Comment by urbach** [comment] 2016-05-19 11:24
I have just summed the 12 propagators obtained with delta sources, and the result agrees up to round off with the "wall source" result. Does this clarify this problem sufficiently?

**Comment by m-schroeck** [comment] 2016-05-19 11:36
While of course each delta source gives identical correlators in each direction as you have confirmed before - this should in fact explain the behavior I guess.
Thanks for checking.

**Comment by urbach** [comment] 2016-05-19 11:41
Thanks to you, Mario. Of course, it would be nice to check analytically why in some directions `sinh` like correlators appear.

**Comment by urbach** [comment] 2016-05-19 13:07
so, could we close this issue @m-schroeck  @kostrzewa ?

**Comment by m-schroeck** [comment] 2016-05-19 13:08
yes

**Closed** 2016-05-19 15:28 UTC
